add (un)set_proxy functions to alias

diff --git a/public/alias b/public/alias
--- a/public/alias
+++ b/public/alias
@@ -152,7 +152,7 @@ function vim4 {
 
 # quick navigation to higher-level directoires
 if is_on_hpc; then
-# avoid overwrite zsh - (cd -)
+  # avoid overwrite zsh - (cd -)
   if is_zsh; then
     alias -="cd ../"
   fi
@@ -185,15 +185,32 @@ if ! is_on_hpc; then
 
   function practice {
     PATH_PRACTICE="$M/codes/code-practice"
-    pdir="$PATH_PRACTICE/$1";
+    pdir="$PATH_PRACTICE/$1"
     if [[ -d "$pdir" ]]; then
       cd "$pdir" || return 1
     else
-      echo "\"$1\" not found under $PATH_PRACTICE"; return 1;
+      echo "\"$1\" not found under $PATH_PRACTICE"
+      return 1
     fi
   }
 fi
 
+# proxy setups, only on local machines
+if ! is_on_hpc; then
+  function set_proxy {
+    _port=7897
+    (($# > 0)) && _port=$1
+    export https_proxy=http://127.0.0.1:$_port
+    export http_proxy=http://127.0.0.1:$_port
+    export all_proxy=socks5://127.0.0.1:$_port
+    unset _port
+  }
+  function unset_proxy {
+    unset http_proxy
+    unset https_proxy
+    unset all_proxy
+  }
+fi
 #=====================================================
 # quick command
 
@@ -218,7 +235,7 @@ function targz {
 
 function tarbz {
   args=("$@")
-  mkdir "$1" && cp -a "${args[@]:1}" "$1" &&  tar --remove-files -jcf "${1}.tar.bz" "${1}"
+  mkdir "$1" && cp -a "${args[@]:1}" "$1" && tar --remove-files -jcf "${1}.tar.bz" "${1}"
 }
 
 function targzd {
@@ -398,8 +415,7 @@ if ! is_zsh; then
   alias gsw='git switch'
   alias gswc='git switch --create'
   alias gta='git tag --annotate'
-  function _gtl()
-  {
+  function _gtl() {
     git tag --sort=-v:refname -n --list "${1}*"
     noglob gtl
   }
@@ -418,12 +434,12 @@ if ! is_zsh; then
 fi
 
 function gac {
-# Auto commit
+  # Auto commit
   datetime=$(date +"%Y-%m-%d %H:%M:%S")
   details=$(git status --porcelain)
   tmpf=$(mktemp)
-  echo -e "Auto commit: $datetime\n\n" > "$tmpf"
-  echo "$details" >> "$tmpf"
+  echo -e "Auto commit: $datetime\n\n" >"$tmpf"
+  echo "$details" >>"$tmpf"
   git commit -F "$tmpf"
 }
 
@@ -550,65 +566,73 @@ fi
 # slurm related
 
 if is_on_hpc; then
-# enter working directory
-  function ej()
-  {
+  # enter working directory
+  function ej() {
     wkd=$(sacct -j $1 -o WorkDir%1000 | awk 'FNR == 3 {print $1}')
     cd "$wkd"
   }
-# query my jobs
-# --me is not available in slurm 19.05.08. For portability, use -u (--user)
+  # query my jobs
+  # --me is not available in slurm 19.05.08. For portability, use -u (--user)
   alias sq="squeue -u $USER -o '%.8i %.18j %.2t %.8M %.3D %.10L %Z'"
-# query jobs in my group. Group is obtained by checking accounting of jobs by sacct
+  # query jobs in my group. Group is obtained by checking accounting of jobs by sacct
   _SLURM_GROUP="$(sacct -n --starttime 1900-01-01 --format=group | head -1)"
   alias sqg="squeue -o '%g %.18j %.8u %.10M %.6D %R' | grep $_SLURM_GROUP"
-# query the number of all jobs, to see the load of the HPC
+  # query the number of all jobs, to see the load of the HPC
   alias sqwc="squeue | wc -l"
 
-# show details of a job
+  # show details of a job
   alias showjob="scontrol show job "
-# show details of a node
+  # show details of a node
   alias shownode="scontrol show node "
 
-# get my jobids
+  # get my jobids
   function _getmyjobids() {
     squeue -u "$USER" -h -o "%A"
   }
   function _getmyrunjobids() {
     squeue -u "$USER" -h -o "%A %T" | awk '/RUNNING/ {print $1}'
   }
-# show the start time of a job
+  # show the start time of a job
   function showjobst() {
     [[ -z "$1" ]] && echo "Usage: showjobst <jobid>" && return 1
     scontrol show job $1 | grep "StartTime="
   }
 
-# show the start time of all my jobs
+  # show the start time of all my jobs
   function showjobstall() {
     alljobss=$(_getmyjobids)
     alljobs=($alljobss)
-    for j in "${alljobs[@]}"; do echo -n "$j "; scontrol show job $j | grep "StartTime="; done | sort
+    for j in "${alljobs[@]}"; do
+      echo -n "$j "
+      scontrol show job $j | grep "StartTime="
+    done | sort
   }
   alias sjta="showjobstall"
 
-# sort and print the working directories of all my jobs
+  # sort and print the working directories of all my jobs
   function showjobdirall() {
     # alljobss=$(squeue -u $(whoami) -h -o "%A" | xargs -I {} scontrol show job {} | grep "WorkDir=" | awk -F= '{print $2}')
     alljobss=$(_getmyjobids)
     # convert to array
     alljobs=($alljobss)
     cwd=$(pwd)
-    for j in "${alljobs[@]}"; do echo -n "$j "; realpath "$(scontrol show job $j | grep 'WorkDir=' | awk -F= '{print $2}')" --relative-to="$cwd"; done | sort
+    for j in "${alljobs[@]}"; do
+      echo -n "$j "
+      realpath "$(scontrol show job $j | grep 'WorkDir=' | awk -F= '{print $2}')" --relative-to="$cwd"
+    done | sort
   }
   alias sjda="showjobdirall"
 
-# sort and print the working directories of my running jobs
+  # sort and print the working directories of my running jobs
   function showjobdirrun() {
     runjobss=$(_getmyrunjobids)
     # convert to array
     runjobs=($runjobss)
     cwd=$(pwd)
-    for j in "${runjobs[@]}"; do echo -n "$j "; realpath "$(scontrol show job $j | grep 'WorkDir=' | awk -F= '{print $2}')" --relative-to="$cwd"; done | sort
+    for j in "${runjobs[@]}"; do
+      echo -n "$j "
+      realpath "$(scontrol show job $j | grep 'WorkDir=' | awk -F= '{print $2}')" --relative-to="$cwd"
+    done | sort
   }
 
   function showjobpwd() {
